[project]
name = "mmdev"
version = "0.1.0"
description = "制造云开发者平台"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.8.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
]
